# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_greeting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='slug',
            field=models.SlugField(blank=True, default=None, null=True),
        ),
    ]
