# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-13 13:50
from __future__ import unicode_literals

from django.db import migrations
from hello.models import Greeting
from django.utils.text import slugify

def slugify_message(apps, schema_editor):
    greetings = Greeting.objects.all()
    for greet in greetings:
        if not greet.slug:
            greet.slug = slugify(greet.message)
            greet.save()


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_greeting_slug'),
    ]

    operations = [
        migrations.RunPython(slugify_message),
    ]
